apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-a
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /demo/$2
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /demo(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-app-cluster
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /demo2/$2
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /demo2(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-app-cluster-2
            port:
              number: 80
---
